config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :reservations
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'reservations#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
    validate :date_before_start
    # validate :start_time_not_sunday
    # validate :start_time_not_saturday
    # validate :time_only
    validates :start_time, uniqueness: { message: 'は他のユーザーが予約しています' }
    validates :end_time, uniqueness: { message: 'は他のユーザーが予約しています' }
  
    def date_before_start
      # binding.irb
      errors.add(:start_time, "には過去の日付を選択できません") if start_time < Date.today
    end
  
    # ◯曜日は選択不可にするようなメソッド
    # def start_time_not_sunday
    #   errors.add(:start_time, "は日曜日を選択できません") if start_time.sunday?
    # end
  
  
    # 指定の日時以外は、予約不可にする処理
    # def time_only
    #   if hour_only_1 && min_only
    #     true
    #   elsif hour_only_2 && min_only
    #     true
    #   else
    #     errors.add(:start_time, "(時間)は13:15もしくは19:15になります")
    #   end
    # end
  
    # def hour_only_19
    #   start_time.hour == 19
    # end
  
    # def hour_only_13
    #   start_time.hour == 13
    # end
  
    # def min_only
    #   start_time.min == 15
    # end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: %i[ show edit update destroy ]

  # GET /reservations or /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1 or /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations or /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)
    # binding.irb
    @reservation.user_id = current_user.id

    # @user = User.find_by(id: @reservation.user_id)
    #binding.irb

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: "Reservation was successfully created." }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1 or /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: "Reservation was successfully updated." }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1 or /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: "Reservation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reservation_params
      params.require(:reservation).permit(:start_time, :end_time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>空き部屋管理システム</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <nav>
          <% if user_signed_in? %>
            <%= link_to 'プロフィール変更', edit_user_registration_path %>
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to 'サインアップ', new_user_registration_path %>
            <%= link_to 'ログイン', new_user_session_path %>
          <% end %>
      </nav>
    </header>

    <p id="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/reservations/_form.html.erb
<%= form_with(model: reservation, local: true) do |form| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
        <% reservation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>予約情報の編集</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to '予約一覧', @reservation %> |
<%= link_to '戻る', reservations_path %>

app/views/reservations/index.html.erb
<h1>空き部屋予約管理</h1>

<br>

<%= month_calendar events: @reservations do |date, reservations| %>
  <%= date.day %>

  <% reservations.each do |reservation| %>
    <% @user = User.find_by(id:reservation.user_id)%>
    <div>
      <%= @user.name %>
      <%= reservation.start_time.hour %>:<%= reservation.start_time.min %>~<%= reservation.end_time.hour %>:<%= reservation.end_time.min %>
    </div>
  <% end %>
<% end %>

<%# ログイン済みのユーザーのみ予約できるような処理 %>
<% if current_user.present? %>
  <%= link_to '予約する', new_reservation_path %>
<% end %>


<br><br>
<br><br>

<table border="1">
  <thead>
    <tr>
      <th>名前</th>
      <th>予約開始時刻</th>
      <th>予約終了時刻</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <% @user = User.find_by(id:reservation.user_id)%>
      <%# binding.irb %>
      <tr>
        <td><%= @user.name %></td>
        <td><%= reservation.start_time.strftime("%Y年%m月%d日%H:%M") %></td>
        <td><%= reservation.end_time.strftime("%m月%d日%H:%M") %></td>
        <%# binding.irb %>
        <% if current_user.present? && reservation.user_id == current_user.id %>
          <%# <td><%= link_to 'Show', reservation %></td>
          <td><%= link_to '編集', edit_reservation_path(reservation) %></td>
          <td><%= link_to '削除', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/reservations/new.html.erb
<h1>新規予約</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to '戻る', reservations_path %>

app/views/reservations/show.html.erb
<p>
  <strong>名前:</strong>
  <% @user = User.find_by(id:@reservation.user_id)%>
  <%= @user.name %>
</p>

<p>
  <strong>予約開始時刻:</strong>
  <%= @reservation.start_time %>
</p>

<p>
  <strong>予約終了時刻:</strong>
  <%= @reservation.end_time %>
</p>

<%= link_to '編集', edit_reservation_path(@reservation) %> |
<%= link_to '予約', reservations_path %>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: "#{start_date.month - 1}月 ⬅️"), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= start_date.year %>年<%= t('date.month_names')[start_date.month] %></span>
    <%= link_to t('simple_calendar.next', default: "➡️ #{start_date.month + 1}月"), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>